### ISSUE TITLE
Dragonfly accelerates distribution of large files with Git LFS

### ISSUE THREAD

**Issue by gaius-qi** [dragonflyoss/Dragonfly2#2965]
### Feature request:
- Git LFS: https://git-lfs.com/.

### TODO List:
- [x] Publish document to Dragonfly website, refer to https://d7y.io/docs/next/setup/integration/git-lfs.
- [x] Finish technical article [Dragonfly accelerates distribution of large files with Git LFS.pdf](https://github.com/dragonflyoss/Dragonfly2/files/13742213/Dragonfly.accelerates.distribution.of.large.files.with.Git.LFS.pdf).
- [x] Publish technical article to CNCF public account in Wechat.
- [x] Publish technical article to [CNCF blog](https://www.cncf.io/blog/), refer to https://www.cncf.io/blog/2024/01/15/dragonfly-accelerates-distribution-of-large-files-with-git-lfs/.
- [x] Publish technical article to [dragonfly_oss](https://twitter.com/dragonfly_oss) twitter.
